Feature/redis monitoring
DFE-Digital/login.dfe.developer-portal pull request #12
Opened 2020-08-26 13:08 UTC by joseluisgraa

2020-08-26 13:11 UTC, DrogoNevets requested changes

2020-08-26 13:11 UTC, DrogoNevets commented on src/controllers/support-access.ts
> +class OfstedController {
SupportAccessController

2020-08-26 13:11 UTC, DrogoNevets commented on src/controllers/support-access.ts
> +        res.redirect('/support-access');
delete file once finished please

2020-08-26 13:11 UTC, DrogoNevets commented on src/views/remove-support.ejs
> +<form action="/support-access" method="post" enctype="multipart/form-data">
can we add some feedback if redirected to this page, something like "users removed" flash message or some such

2020-08-26 13:12 UTC, joseluisgraa commented on src/controllers/support-access.ts
> +class OfstedController {
ah yes I saw it and forgot to fix it

2020-08-26 13:12 UTC, joseluisgraa commented on src/controllers/support-access.ts
> +        res.redirect('/support-access');
ok will do

2020-08-26 13:13 UTC, joseluisgraa commented on src/views/remove-support.ejs
> +<form action="/support-access" method="post" enctype="multipart/form-data">
I added logging in console, thought about feedback here but didn't know how it works with EJS so left it. Let me have a look.

2020-08-27 10:01 UTC, DrogoNevets approved these changes

2020-08-27 10:01 UTC, DrogoNevets commented on src/controllers/support-access.ts
> +    private renderView(req: Request, res: Response, opts?: IRemoveSupportResult) {
consider setting default value (shouldnt be needed though) you can do an `if` in the EJS too

2020-08-27 10:01 UTC, DrogoNevets commented on src/controllers/support-access.ts
> +                opts: opts || new RemoveSupportResult()
if default value set the OR isnt needed

2020-08-27 10:01 UTC, DrogoNevets commented on src/views/remove-support.ejs
> +<% if (opts.error) { %>
1) try if(opts?.error)
2) if that fails if(opts && opts.error)

2020-08-27 10:01 UTC, DrogoNevets commented on src/views/remove-support.ejs
> +<% if (opts.result) { %>
1) try if(opts?.result)
2) if that fails if(opts && opts.result)

2020-08-27 10:21 UTC, DrogoNevets approved these changes

2020-08-27 10:26 UTC, merged